
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "email": "email@yahoo.com",
    "password": "PassW0rd",
    "firstname": "first",
    "lastname": "last",
    "role": "DOCTOR"
}